// Initial playtest values, recorded in ARCHITECTURE.md; all distances are metres.
export const GAMEPLAY = {
  tickMs: 50,
  moveSpeed: 6,
  playerRadius: 0.45,
  jumpSpeed: 7,
  gravity: 18,
  interactionHeight: 0.9,
  frostProjectileSpeed: 18,
  frostProjectileRadius: 0.32,
  frostProjectileHitRadius: 0.78,
  frostProjectileLifetimeMs: 1_800,
  frostThrowCooldownMs: 700,
  maxFrostProjectiles: 64,
  rescueRange: 2.4,
  rescueMs: 1500,
  protectionMs: 2000,
  rescueLeaseMs: 350,
  helpCooldownMs: 5000,
  helpDurationMs: 2500,
  inputExpiryMs: 250,
  maxInputQueue: 5,
  interpolationMs: 100,
  knockbackSpeed: 10,
  knockbackVerticalSpeed: 3,
  knockbackDecay: 0.85,
  // Match timing (milliseconds)
  regularMs: 30_000,
  warningMs: 8_000, // warning phase begins this many ms before the regular deadline
  deepFreezeMs: 30_000,
  roundResultMs: 5_000,
  matchResultMs: 10_000,
  maxRounds: 5,
} as const;
