import fs from 'node:fs';
import { Mesh, Scene, Vector3 } from 'three';
import { OriginalWorldMap } from '../apps/client/src/world/original-world-map.js';

// Bake the same procedural meshes the browser renders. River tops remain the
// authored walkable channel floors. The riverbank beds overlap the grid cells
// removed around each channel, so their top groups enter collision to close bank
// gaps; their opaque support skirts remain presentation so they cannot become
// invisible movement barriers. The ocean volume, route paint, and boundary remain
// presentation. The deep ocean floor is handled by the shared analytic plane.
const world = new OriginalWorldMap(new Scene());
world.group.updateMatrixWorld(true);
const coordinates: number[] = [];
const vertex = new Vector3();
world.group.traverse((object) => {
  if (!(object instanceof Mesh)) return;
  if (
    object.name.startsWith('OCEAN') ||
    object.name === 'frost-wall' ||
    object.name.startsWith('PATH_') ||
    object.name.startsWith('WF_')
  )
    return;
  const positions = object.geometry.getAttribute('position');
  const indices = object.geometry.index;
  const channelTop =
    object.name === 'WATER_NETWORK' || object.name === 'RIVERBED_NETWORK'
      ? object.geometry.groups.find(
          (group: { materialIndex?: number }) => group.materialIndex === 0,
        )
      : undefined;
  const start = channelTop?.start ?? 0;
  const count = channelTop?.count ?? indices?.count ?? positions.count;
  for (let offset = 0; offset < count; offset++) {
    const i = start + offset;
    vertex.fromBufferAttribute(positions, indices ? indices.getX(i) : i);
    vertex.applyMatrix4(object.matrixWorld);
    for (const value of [vertex.x, vertex.y, vertex.z]) {
      const quantized = Math.round(value * 100);
      if (quantized < -32768 || quantized > 32767)
        throw new Error('Original world exceeds collision encoding bounds');
      coordinates.push(quantized);
    }
  }
});
const bytes = Buffer.alloc(coordinates.length * 2);
coordinates.forEach((value, index) => bytes.writeInt16LE(value, index * 2));
fs.writeFileSync(
  'packages/shared/src/simulation/original-data.ts',
  `// Generated by npm run assets:original. Centimetre-quantized restored world meshes.\nexport const ORIGINAL_TRIANGLES_BASE64: string =\n  '${bytes.toString('base64')}';\n`,
);
world.destroy();
console.log(`Original World: ${coordinates.length / 9} collision triangles, ${bytes.length} bytes`);
